### ISSUE TITLE
Add Temperature as Dimension

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Dimensions#10]
Right now there is only Kelvin and I think this is not how it should be
What about we have a Temperature dimension with Kelvin, Celcius, Fahrenheit etc..

@Yuri05 @UlrichSi. thoughts?

Temperature is a required input for the upcoming dermal model. We might as well get the dimension in asap

**Comment by Yuri05** [comment]
we would need to extend our unit calculation and definition with an "offset".
Currently it's just `unit1=factor*unit2`. Would be then `unit1=factor*unit2+offset`

**Comment by msevestre** [comment]
we have offset already

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/b92fd6987e705ce03963b29e37adfb1e15bcdada/src/OSPSuite.Core/Domain/UnitSystem/Unit.cs#L19

**Comment by Yuri05** [comment]
>we have offset already

cool :)

**Comment by UlrichSi** [comment]
I am not sure if we really need Celsius, Fahrenheit - maybe even the Réaumur temperature scale is asked for?! For biophysical calculations, Kelvin should suffice.

**Comment by msevestre** [comment]
The tester of our model are potentially MD and do not work in Kelvin lol

**Comment by UlrichSi** [comment]
So what temperature does an MD measure except body temperature? I do not see a use case here.

**Comment by msevestre** [comment]
The dermal model use "Ambient Temperature" as an input. The viscosity of a gel for example is HIGHLY affected by the outside temperature. 
I'd suggest to not  ask people to enter the outside temperature in Kelvin

**Comment by Yuri05** [comment]
just to be complete ;)

![grafik](https://user-images.githubusercontent.com/25061876/55482960-e2c74680-5625-11e9-83bf-9c6b05451cdb.png)

**Comment by msevestre** [comment]
Which begs the question. Should't our temperature system use Celcius as baseunit?

**Comment by msevestre** [comment]
For the user it won't make any difference. Just for looking at model values, it might be easier to reason about

**Comment by UlrichSi** [comment]
We often have input values that need to be converted prior to entering them into the OSP suite. Like having concentrations in "Units" - which is specific for a particular substance or substance pair (like enzyme and one particular substrate). Common temperature scales might be worth adding, however, even if it is just that single use case.

Very often, only temperature **differences** are used in a model's formula. In that case, there is no difference between Celsius and Kelvin. Or we have formulas using Kelvin - but hardly anybody will use Arrhenius' formula (https://en.wikipedia.org/wiki/Arrhenius_equation) to calculate a rate constant as function of temperature when only the extrapolation to 37°C is needed.

**Comment by msevestre** [comment]
>It is dumb enough that we use minutes for time!

Interesting. Why is it dumb?
Ok base unit is going to be kelvin in that case

**Comment by UlrichSi** [comment]
> 
> 
> > It is dumb enough that we use minutes for time!
> 
> Interesting. Why is it dumb?
> Ok base unit is going to be kelvin in that case

Most scientific journals require that data are published in SI units, which includes rate constants to be based on seconds. And temperatures in Kelvin. Things are easier to convert, if one adheres to SI units.

**Comment by msevestre** [comment]
You can define display units in mobi and have all your constant converted automagically for you. 

To be honest, the amount of gain for the small pain (how often do we publish rate constants :)) makes that collegial decision all but dumb I believe
