### ISSUE TITLE
add ug/cm2 and ug/cm2/h to Mass per area and Mass per area per time

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.Dimensions#16]
More natural units for some applications.  Need them in allUnits, toBaseUnit etc.  Currently only have mg/m2 and km/dm2

![image](https://user-images.githubusercontent.com/18409098/75626595-b6e67500-5b96-11ea-8e6a-ed377c951418.png)

**Comment by msevestre** [comment]
@abdullahhamadeh Can you submit a pull request please?

I have moved the issues to the dimension repo

**Comment by msevestre** [comment]
Well in fact it's already there

<Dimension name="Mass per area" baseUnit="kg/dm²" defaultUnit="µg/cm²">
      <BaseRepresentation lengthExponent="-2" massExponent="1" timeExponent="0" electricCurrentExponent="0" temperatureExponent="0" amountExponent="0" luminousIntensityExponent="0" />
      <Units>
        <Unit name="µg/cm²" factor="1E-7" />
        <Unit name="mg/cm²" factor="1E-4" />
        <Unit name="mg/m²" factor="1E-8" />
        <Unit name="kg/dm²" factor="1" visible="0" />
      </Units>
    </Dimension>
    <Dimension name="Mass per time" baseUnit="kg/min">
      <BaseRepresentation lengthExponent="0" massExponent="1" timeExponent="-1" electricCurrentExponent="0" temperatureExponent="0" amountExponent="0" luminousIntensityExponent="0" />
      <Units>
        <Unit name="kg/min" factor="1" />
        <Unit name="g/min" factor="1E-3" />
        <Unit name="mg/min" factor="1E-6" />
        <Unit name="µg/min" factor="1E-9" />
        <Unit name="ng/min" factor="1E-12" />
        <Unit name="pg/min" factor="1E-15" />
        <Unit name="kg/s" factor="1*60" />
        <Unit name="g/s" factor="1E-3*60" />
        <Unit name="mg/s" factor="1E-6*60" />
        <Unit name="µg/s" factor="1E-9*60" />
        <Unit name="ng/s" factor="1E-12*60" />
        <Unit name="pg/s" factor="1E-15*60" />
      </Units>
    </Dimension>

**Comment by abdullahhamadeh** [comment]
My mistake.  It is Dose per body surface area that can use ug/cm2, not mass per area.

**Comment by msevestre** [comment]
This dimension is generally a Input Only dimension used for PK-Sim. I can imagine that the Dose per surface area is a dimension that is not required.
