### ISSUE TITLE
Further unit synonyms?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Dimensions#21]
E.g. m2 for m², m3 for m³, ... ?

**Comment by Yuri05** [comment]
FYI @ju-rgen @sfrechen @Christoph27 @Sulav1

**Comment by msevestre** [comment]
This is already taken care of programatically
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/UnitSystem/Unit.cs#L56
