### ISSUE TITLE
Add `g/xxx` for `DosePerBodyWeight`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Dimensions#22]
Only `mg/kg` and `kg/kg` are available now. Would be good to also have at least `g/kg`.

**Comment by msevestre** [comment]
There is one dimension that is only internal. Is it possible that it is this one?

**Comment by PavelBal** [comment]
It is the default parameter to change the body-weight scaled dosing.

**Comment by msevestre** [comment]
>the body-weight scaled dosing. 

What parameter is this?

**Comment by msevestre** [comment]
ok found it
