### ISSUE TITLE
Wrong definition of dimension "Katal" 

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/OSPSuite.Dimensions#5]
From what I can see, the catalytic activity one "Katal" (1 kat) appears to be wrongly defined as 1 mol/min by default. It should be 1 mol/s, as can be verified here:
https://en.wikipedia.org/wiki/Katal

In addition, we may also want to add the still widespread "enzyme unit" by adding "µmol/min" to the drop-down selection menu.

To reproduce, create a new project and open the spatial structure. Then add a parameter with the dimension "Katal" to "Organism". Use "Utilities/Manage Project Display Units" and "Update all display units" to change the unit. "1 kat" will then be wrongly converted to "0.017 mol/s".

**Comment by msevestre** [comment]
Actually this whole dimension is not defined properly. The default is mol/min but it should actually be umol/min in order to match with our itnernal base unit!

**Comment by UlrichSi** [comment]
Putting the default to µmol/min is fine with me, but the manually selectable "Katal" should become mol/s - see above.

**Comment by msevestre** [comment]
Not the default but the base unit. Right now not only was kat wrong but any value used in the model was wrong. Where is this unit used?

**Comment by UlrichSi** [comment]
The unit is used as alternative for "amount" of a catalyst. Sometimes you do not know or do not care about mg amounts; from "catalytic activity" you can directly calculate Vmax in a Michaelis-Menten or pseudo linear kinetics equation. Details are described in the above linked Wikipedia article.

**Comment by msevestre** [comment]
@UlrichSi @Yuri05 
Well hopefully this dimension was not used all that much... because a factor 1e6 difference between the value and the displayed value could be significant :)

**Comment by UlrichSi** [comment]
@msevestre Sure enough! To my knowledge it is not used in PK-Sim, but may be relevant in "hand-made" MoBi models.
