### ISSUE TITLE
Default unit of some dimension is too weird to be correct

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Dimensions#7]
The default unit is what is being selected by DEFAULT. It should be what people use, not some weird internal unit!!

- `Lux` default unit is `(cd*sr)/dm²` and not `lx`?
- `Ohm` default unit is `(kg*dm²)/(A²*min³)` and not `Ohm`
- `Radian` default unit is `dm/dm` and not `rad`
- `Siemens` defaukt unit is `(A²*min³)/(kg*dm²)` and not `S` etc..

This should be changed in my opinion

@Yuri05 @UlrichSi agreed?

**Comment by msevestre** [comment]
This will not required any project conversion. Just the default display will be changed

**Comment by UlrichSi** [comment]
@msevestre the suggested changes sound reasonable. The radian is actually yet another dimensionless, but specifically named unit. 

I wonder if any of the above units have been ever used in any model.
